services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: lumi
      POSTGRES_PASSWORD: lumi
      POSTGRES_DB: lumi

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: